[project]
name = 'Decentralized-Intellectual-Property-Registry'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.creation-registry]
path = 'contracts/creation-registry.clar'
clarity_version = 2
epoch = 2.5

[contracts.licensing]
path = 'contracts/licensing.clar'
clarity_version = 2
epoch = 2.5

[contracts.ownership]
path = 'contracts/ownership.clar'
clarity_version = 2
epoch = 2.5

[contracts.royalty]
path = 'contracts/royalty.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
